# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-15 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stars', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('is_open', models.IntegerField()),
                ('attributes', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('hours', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('business_id', models.CharField(max_length=50)),
                ('stars', models.FloatField()),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('useful', models.IntegerField()),
                ('funny', models.IntegerField()),
                ('cool', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('review_count', models.IntegerField()),
                ('yelping_since', models.DateTimeField()),
                ('friends', models.CharField(max_length=100)),
                ('useful', models.IntegerField()),
                ('funny', models.IntegerField()),
                ('cool', models.IntegerField()),
                ('fans', models.IntegerField()),
                ('elite', models.CharField(max_length=50)),
                ('averages_stars', models.FloatField()),
            ],
        ),
    ]
