# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-16 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181216_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(max_length=50),
        ),
    ]
